### ISSUE TITLE
"Filter" prevents auto data refresh

### ISSUE THREAD

**Issue by amalik886** [peterfriese/MakeItSo#1]
Hello,

Introducing .whereField("userId", isEqualTo: self.userId) in repository's loadData() is preventing auto data refresh.

**Comment by peterfriese** [comment]
I just tried reproducing this, but things worked at expected.

Can you provide exact steps to repro, @amalik886 ?

**Comment by amalik886** [comment]
Hi @peterfriese,

I was missing composite index, which was preventing auto refresh.

Thank you for looking into it and for the awesome code. Closing the issue.
