### ISSUE TITLE
Sign In with Apple doesn't work with ios 14 Simulator

### ISSUE THREAD

**Issue by byan7** [peterfriese/MakeItSo#16]
Hi, this seems like bug with Xcode 12/ios 14 simulator, but Apple Sign in doesn't work in ios-14 simulator using this project code. When entering the password the screen just hangs and nothing happens. 
With log:
2020-07-02 17:09:07.433852+0300 byan[86378:2354436] 6.27.0 - [Firebase/Firestore][I-FST000001] WatchStream (60000368b218) Stream error: 'Unavailable: Network connectivity changed'
2020-07-02 17:09:17.206022+0300 byan[86378:2354436] [core] Authorization failed: Error Domain=AKAuthenticationError Code=-7071 "(null)"
Sign in with Apple errored: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

But it works fine with ios-13. I'm using Xcode 12 MacOs Catalina 10.15.5.

**Comment by peterfriese** [comment]
Hi @byan7, thanks for reporting this - I hadn't noticed myself.

It seems like this is an issue with the Simulator - see [this thread](https://developer.apple.com/forums/thread/651533) on the Apple Developer Forums. I was able to confirm this behaviour with Apple's [Juice sample app](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple).

Running on a physical device works fine - so as long as you've got access to a testing device, that should unblock you.

I will keep an eye on this and check back when Apple releases the next beta.
