### ISSUE TITLE
Use TestDataTaskRepository in View Preview

### ISSUE THREAD

**Issue by cytrix86** [peterfriese/MakeItSo#2]
Hi,

first of all thanks for your great work. It is really a massive help for someone just starting with SwiftUI and Firebase.

I was looking for a solution to keep the TestDataTaskRepository providing the Data for the preview of the TaskListView so making changes to the cell still becomes visible while running the app uses the Firebase repository - as I am quite new to SwiftUI and especially Resolver if couldn't figure it out.

Thank you in advance.

Kind reagards

**Comment by peterfriese** [comment]
Hi @cytrix86 - thanks for the kind words!

To achieve this, you can change the `PreviewProvider` in `TaskListView`, like so:

```swift
struct TaskListView_Previews: PreviewProvider {
  static var previews: some View {
    let vm = TaskListViewModel()
    vm.taskRepository = TestDataTaskRepository()
    return TaskListView(taskListVM: vm)
  }
}
```

Hope this helps.

Cheers,
Peter

**Comment by cytrix86** [comment]
Hi Peter,

Thanks for your help. It does not work instantly because of the change in the Tasks id for Firebase. I changed the test data accordingly:

`#if DEBUG
let testDataTasks = [
    Task(id: UUID().uuidString, title: "Implement UI", priority: .medium, completed: true),
    Task(id: UUID().uuidString, title: "Connect to Firebase", priority: .medium, completed: false),
    Task(id: UUID().uuidString, title: "????", priority: .high, completed: false),
    Task(id: UUID().uuidString, title: "PROFIT!!!", priority: .high, completed: false)
]
#endif`

I also tried to change the Resolver injection with and conditional `#if DEBUG` but that affects the Simulator as well. At the moment I am changing it manually - can you think of a more elegant solution? 

Cheers,
Fabian
