### ISSUE TITLE
Migrating user data

### ISSUE THREAD

**Issue by hoschkara** [peterfriese/MakeItSo#35]
Thanks for the great tutorial.
I would really like to see that last piece come into play, which is the migration of the anonymous user data in case a user reinstalls the apps, makes more changes even though he has signed up before, and then tries to sign in again. Do you think you could add this in a separate post or point to a solution?

**Comment by peterfriese** [comment]
Thanks for the kind words, @hoschkara !

Writing (and vlogging) about this solution is high up on my list. I will update this issue as I make progress. Would you be interested in providing feedback on a draft of the article?

**Comment by hoschkara** [comment]
It would be a pleasure!

**Comment by peterfriese** [comment]
Ok, great - can you DM me your email address (my Twitter DMs are open), and I'll invite you to the Google doc.

**Comment by hoschkara** [comment]
I don't use twitter, but email is stefan@hoschkara.com, also schreib mir einfach :)

**Comment by hoschkara** [comment]
You got this message @peterfriese?

**Comment by peterfriese** [comment]
I did - hope to start working on the draft this week :-)

**Comment by hoschkara** [comment]
How is it going? :)

**Comment by hoschkara** [comment]
Not trying to be annoying at all, but do you have an approximate release date for the tutorial? Just for me to plan my own agenda :)

**Comment by hoschkara** [comment]
I will, thanks!

**Comment by peterfriese** [comment]
Implementation [merged into the main branch](https://github.com/peterfriese/MakeItSo/tree/d4c4fdc2e1133273f3a5312d5728fa1881913915).
The article is now published at https://peterfriese.dev/replicating-reminder-swiftui-firebase-part4/

Hope this helps - feel free to leave feedback.
