### ISSUE TITLE
error: Build input file cannot be found: '/Users/user/Desktop/MakeItSo/final/MakeItSo/MakeItSo/GoogleService-Info.plist' when building project

### ISSUE THREAD

**Issue by acridmaqoi** [peterfriese/MakeItSo#37]

**Comment by peterfriese** [comment]
Hi @acridmaqoi,

You need to register your app on Firebase, download the `GoogleService-Info.plist` file from the Firebase console, and drag it into the Xcode project.

- Here's the [getting started guide](https://firebase.google.com/docs/ios/setup) in the Firebase docs
- Here's a [video in which I walk through](https://www.youtube.com/watch?v=4RUeW5rUcww&list=PL0k0xRXA0PWFU0yD4PGp7z_-m6zhkndak&index=8) the process of building this app
- Here's a [blog post series](https://peterfriese.dev/replicating-reminder-swiftui-firebase-part1/) that explains how I built the app. In [part 2](https://peterfriese.dev/replicating-reminder-swiftui-firebase-part2/), I show how to connect the app to Firebase

Hope this helps!

**Comment by acridmaqoi** [comment]
> Hi @acridmaqoi,
> 
> You need to register your app on Firebase, download the `GoogleService-Info.plist` file from the Firebase console, and drag it into the Xcode project.
> 
> * Here's the [getting started guide](https://firebase.google.com/docs/ios/setup) in the Firebase docs
> * Here's a [video in which I walk through](https://www.youtube.com/watch?v=4RUeW5rUcww&list=PL0k0xRXA0PWFU0yD4PGp7z_-m6zhkndak&index=8) the process of building this app
> * Here's a [blog post series](https://peterfriese.dev/replicating-reminder-swiftui-firebase-part1/) that explains how I built the app. In [part 2](https://peterfriese.dev/replicating-reminder-swiftui-firebase-part2/), I show how to connect the app to Firebase
> 
> Hope this helps!

thanks, sorry if it was a noob question, am a beginner
