### ISSUE TITLE
Broken link in the website

### ISSUE THREAD

**Issue by mertnesvat** [peterfriese/MakeItSo#4]
Your posts are great keep going 💯 

Not a huge deal but I noticed the links are broken in this post below for the repository,

https://peterfriese.dev/replicating-reminder-swiftui-firebase-part1/ 

wanted inform

thanks

**Comment by peterfriese** [comment]
Thanks for letting me know. Fixed in 
* https://peterfriese.dev/replicating-reminder-swiftui-firebase-part1/
* https://medium.com/better-programming/replicating-the-ios-reminders-app-part1-44211a7b7029
