### ISSUE TITLE
Sign In with Apple doesn’t work

### ISSUE THREAD

**Issue by jamiedaniel** [peterfriese/MakeItSo#7]
With the new update of Swift 5.2 the final app no longer allows. 

Error is any the user has logged out, even though the user hasn’t ever logged in.

All settings have been cleared, new iPhone install, new Firebase project, app id and applied websites cleared.

Error still persists.

**Comment by peterfriese** [comment]
Hi @jamiedaniel - thanks for your report. Not sure I understand what the problem is - can you post the error message you see?

Please also make sure to enable _Sign in with Apple_ in your Firebase project:

![firebase_enable_siwa](https://user-images.githubusercontent.com/232107/79726458-1fc2b180-82eb-11ea-8c79-303ab0e04b76.png)

**Comment by jamiedaniel** [comment]
peterfriese
I cleared the appleid dependency. I cleared the app and I re-read the documentation. I can't get my code or your code to work properly. Here is where I am trying to get it to work with another piece of code. Maybe this will help you understand where my lack of understanding begins:

`//
//  ViewController.swift

import UIKit
import Firebase
import FirebaseAuth
import FirebaseUI
import AuthenticationServices

class ViewController: UIViewController, FUIAuthDelegate {
    
    var ref: DatabaseReference!
    var databaseHandle: DatabaseHandle!
    var userID = ""
    var userTokens = ""
    var theUser: Firebase.User?
    
    func authUI(_ authUI: FUIAuth, didSignInWith user: FirebaseAuth.User?, error: Error?) {
        if error != nil {
			print("***************************")
            print("There was an error with a login. Error description follows")
            print("***************************")
            print(error?.localizedDescription)
            print("***************************")
        } else {
            
			// add user information to the database
            ref.child("users").child((Auth.auth().currentUser?.uid)!).updateChildValues(["email" : Auth.auth().currentUser?.email! as Any])
            ref.child("users").child((Auth.auth().currentUser?.uid)!).updateChildValues(["provider" : Auth.auth().currentUser?.providerID as Any])
            let name = Auth.auth().currentUser?.displayName
            let splitName = name?.components(separatedBy: " ")
            ref.child("users").child((Auth.auth().currentUser?.uid)!).updateChildValues(["firstname" : splitName?.first ?? ""])
            ref.child("users").child((Auth.auth().currentUser?.uid)!).updateChildValues(["lastname" : splitName?.last ?? ""])
            
            UserDefaults.standard.set(Auth.auth().currentUser?.uid, forKey: Constants.NSUserDefaultsKeys.USER_KEY)
            
            self.loadDashboard()
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureDatabase()
		
        checkLoggedIn() // Check if there is a user logged in.
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
	}
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
    }
    
    func checkLoggedIn() {
        Auth.auth().addStateDidChangeListener{ auth, user in
            if user != nil {
                self.userID = (user?.uid)!
                self.theUser = user
                UserDefaults.standard.set(Auth.auth().currentUser?.uid, forKey: Constants.NSUserDefaultsKeys.USER_KEY)
                
                self.loadDashboard()
                
            } else {
                self.login()
            }
        }
    }
    
    //MARK: Load the dashboard after authentication
    func loadDashboard() {
        // Load dashboard
        if theUser != nil {
            let dashboardViewController = self.storyboard?.instantiateViewController(withIdentifier: "DashTabBarController")
            dashboardViewController?.modalPresentationStyle = UIModalPresentationStyle.fullScreen
            self.present(dashboardViewController!, animated: true, completion: nil)
        }
    }
    
    func login() {
        
        let authUI = FUIAuth.init(uiWith: Auth.auth())
        let providers: [FUIAuthProvider] = [
            FUIGoogleAuth(),
            FUIEmailAuth(),
            FUIOAuth.appleAuthProvider()
        ]
        
        authUI?.providers = providers
        authUI?.delegate = self
        
        
        let authViewController = authUI?.authViewController()
        authViewController?.modalPresentationStyle = .fullScreen
        self.present(authViewController!, animated: false, completion: nil)
        
    }
    
    func authPickerViewController(forAuthUI authUI: FUIAuth) -> FUIAuthPickerViewController {
        return MyCustomAuthPickerViewController(authUI: authUI)
    }
    
    func configureDatabase() {
        ref = Database.database().reference()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {
        let sourceApplication = options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String?
        if FUIAuth.defaultAuthUI()?.handleOpen(url, sourceApplication: sourceApplication) ?? false {
            return true
        }
        return false
    }
    
}
`

**Comment by peterfriese** [comment]
Thanks for providing the code snippet, @jamiedaniel - do I understand correctly that both my SwiftUI sample and the code snippet you pasted (which uses FirebaseUI / UIKit) fail?

Can you provide an error message, or a screen recording that shows how SiwA fails for you in Make It So?

**Comment by jamiedaniel** [comment]
This is the entire log for the following actions:
- Build and Deploy to real device (iPhone Max Pro) Internet connection FIBER
- add task. Task doesn't show up on phone but does show up in Firestore after refresh of browser.
- login to Apple.
- Login to apple asks the prerequisite questions. The interface spins and then stops on the same screen that says Sign in with Apple button.
- Checked authentication tab in Firebase - nothing
- Checked log - nothing

Logs follow:

`2020-04-20 11:37:48.827915-0400 Make It So[4773:1326066]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2020-04-20 11:37:48.903732-0400 Make It So[4773:1326071] 6.13.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60106000 started
2020-04-20 11:37:48.904647-0400 Make It So[4773:1326071] 6.13.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Using Cloud Firestore in production
Sign in state has changed.
User signed out.
2020-04-20 11:37:49.727539-0400 Make It So[4773:1326064] 6.13.0 - [Firebase/Firestore][I-FST000001] Listen for query at tasks failed: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/makeitso2test/firestore/indexes?create_composite=Cktwcm9qZWN0cy9tYWtlaXRzbzJ0ZXN0L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy90YXNrcy9pbmRleGVzL18QARoKCgZ1c2VySWQQARoPCgtjcmVhdGVkVGltZRABGgwKCF9fbmFtZV9fEAE
2020-04-20 11:37:56.103400-0400 Make It So[4773:1326065] [general] Connection to daemon was invalidated
2020-04-20 11:38:03.959897-0400 Make It So[4773:1326064] 6.13.0 - [Firebase/Analytics][I-ACS023130] Configuration not found. Using default configuration
`

**Comment by peterfriese** [comment]
Thanks, @jamiedaniel - did you create the composite index, as mentioned in the error message? This is mentioned in part 2 of the blog series: https://peterfriese.dev/replicating-reminder-swiftui-firebase-part2/ (search for `compound query`).

**Comment by jamiedaniel** [comment]
I have added all those. Changed the Firestore indexes et al. Still not signing with Apple.

Log follows:

`020-04-20 13:09:37.812154-0400 Make It So[4898:1366759]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2020-04-20 13:09:37.899859-0400 Make It So[4898:1366761] 6.13.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60106000 started
2020-04-20 13:09:37.900464-0400 Make It So[4898:1366761] 6.13.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Using Cloud Firestore in production
Sign in state has changed.
User signed out.
2020-04-20 13:09:38.735170-0400 Make It So[4898:1366761] 6.13.0 - [Firebase/Firestore][I-FST000001] Listen for query at tasks failed: Missing or insufficient permissions.
2020-04-20 13:09:43.280623-0400 Make It So[4898:1366759] [] tcp_input [C2.1:3] flags=[R] seq=2521190804, ack=0, win=0 state=LAST_ACK rcv_nxt=2521190804, snd_una=2850931685
2020-04-20 13:09:43.283961-0400 Make It So[4898:1366759] [] tcp_input [C2.1:3] flags=[R] seq=2521190804, ack=0, win=0 state=CLOSED rcv_nxt=2521190804, snd_una=2850931685
2020-04-20 13:09:43.284216-0400 Make It So[4898:1366759] [] tcp_input [C2.1:3] flags=[R] seq=2521190804, ack=0, win=0 state=CLOSED rcv_nxt=2521190804, snd_una=2850931685
2020-04-20 13:10:15.892398-0400 Make It So[4898:1366763] [general] Connection to daemon was invalidated`

**Comment by jamiedaniel** [comment]
@peterfriese I have added all the indexes, created the data model, used your listed firestorm rules, setup the Xcode Sign in with Apple., setup firebase Authorization to use Sign In with Apple.

When I tap the sign in and the animation spins to elude to the fact that I am being logged in with Apple, the interface goes back to the same screen. Doesn't give an error and doesn't actually do anything.

What am I missing?

**Comment by ToddKerpelman** [comment]
The error message mentions " Listen for query at tasks failed: Missing or insufficient permissions." -- probably your security rules don't allow reads.

**Comment by jamiedaniel** [comment]
@ToddKerpelman they are from the Part 2 of his tutorial:

`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /tasks/{task} {
    	allow write: if request.auth.uid != null 
                     && request.resource.data.userId == request.auth.uid; // (1)
      allow read: if resource.data.userId == request.auth.uid; // (2)
    }
  }
}`

**Comment by ToddKerpelman** [comment]
Hmmm... I see a lot of writing to the "users" collection in the "authUI:didSignInWithUser" function, and nothing about that in the security rules. Are you sure that's not the cause?

**Comment by jamiedaniel** [comment]
@ToddKerpelman I'm open to ANY and all suggestions. I have checked out the repo and went into the FINAL folder to see how it should work when completed. It doesn't I have setup everything from indexes to plists to apple emails responders. 

It *should* write to the authenticated users of the project and I *should* be able to see new new user in the list. No dice.

I'm wondering in the project config that wasn't listed that it depends on.

Any ideas to troubleshoot ..? I'm open to any and all ideas at this point...

(I can't learn to the get the display name of the currentUser if I can't create a user :) )

**Comment by jamiedaniel** [comment]
> Hmmm... I see a lot of writing to the "users" collection in the "authUI:didSignInWithUser" function, and nothing about that in the security rules. Are you sure that's not the cause?

@ToddKerpelman  Are you talking about my code or the code from the tutorial that @peterfriese published in 3 parts?

**Comment by jamiedaniel** [comment]
@ToddKerpelman @peterfriese I have traced your code over the past few hours. It goes to .link and never completes a sign in. Line 174 always returns Auth.auth().currentUser == nil

I'm at a loss here.

**Comment by peterfriese** [comment]
It seems like you might not have enabled _Anonymous Auth_ in your project. Both _Anonymous Auth_ and _Sign in with Apple_ need to be enabled.

**Comment by jamiedaniel** [comment]
Sorry I finally got around to looking more into this and that was something that was overlooked. In our apps we never authorize anonymous because of the security requirements. That worked like a charm.
