### ISSUE TITLE
App is stuck building without failing or success 

### ISSUE THREAD

**Issue by byan7** [peterfriese/MakeItSo#8]
Hi, I dowloaded the project and installed the pods and google-info file but the app gets stuck building without completing.

**Comment by peterfriese** [comment]
Thanks for your report!

Can you provide more details, such as Xcode version, etc? Along or a screenshot would also be useful. 

Thanks!

**Comment by byan7** [comment]
For some reason after going back to my personal project and fixing some things I reopened this project and now it builds fine and everything works perfectly! Xcode is truly a terrible IDE. 
Thanks for sharing this!
