### ISSUE TITLE
New task text disappearing

### ISSUE THREAD

**Issue by hou1nxb** [peterfriese/MakeItSo#9]
Hi - thanks for sharing this code.

Xcode: 11.4.1
Simulator: iPhone 11 / iOS 13.4.1

I am seeing an issue when adding a new task - after typing in the task text and tapping return on simulator keyboard or enter on the actual computer keyboard, the new row disappears. I verified the task is showing up in Firebase right away. If you kill the app and re-open, the task then shows up. I am also seeing this on my iPhone with iOS 13.3.1. Was wondering if you can reproduce this issue. Thanks so much.

Nick

**Comment by peterfriese** [comment]
Hey Nick,

thanks for reaching out! This sounds like you haven't yet set up the index for the composite query.

Have a look into the Xcode console, there should be an error message including a link to create the index.

Let me know if this helps.
Thanks,
Peter

**Comment by hou1nxb** [comment]
Hi Peter,

Thanks for the response. Sure enough - that was it. I was looking back through your article (pt.2) and found the paragraph where you mention this. Somehow I completely missed it on my first pass. My apologies. Cheers!.

Nick

**Comment by peterfriese** [comment]
Awesome, I'm glad it worked out!
